# Generated by Django 4.0.4 on 2022-05-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPago',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stays.pago',),
        ),
    ]
