# Generated by Django 4.0.4 on 2022-05-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_alter_ticket_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyTicket',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stays.ticket',),
        ),
    ]
